// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3FynZArruuQ6W0RHu2aQ-C74baEWTaLA',
    appId: '1:1075186320999:web:448ddbe42a02cc293ef6c2',
    messagingSenderId: '1075186320999',
    projectId: 'adv-final-examfb',
    authDomain: 'adv-final-examfb.firebaseapp.com',
    storageBucket: 'adv-final-examfb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy-niTl-0JX7mZJBcAJEAGaMqM6DfjE_U',
    appId: '1:1075186320999:android:d101132ed406a5243ef6c2',
    messagingSenderId: '1075186320999',
    projectId: 'adv-final-examfb',
    storageBucket: 'adv-final-examfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYf3-8zVmRuufQ8sri1jFUfuVyfZAzPxc',
    appId: '1:1075186320999:ios:66927f3674dda17a3ef6c2',
    messagingSenderId: '1075186320999',
    projectId: 'adv-final-examfb',
    storageBucket: 'adv-final-examfb.firebasestorage.app',
    iosBundleId: 'com.example.avdFinalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYf3-8zVmRuufQ8sri1jFUfuVyfZAzPxc',
    appId: '1:1075186320999:ios:66927f3674dda17a3ef6c2',
    messagingSenderId: '1075186320999',
    projectId: 'adv-final-examfb',
    storageBucket: 'adv-final-examfb.firebasestorage.app',
    iosBundleId: 'com.example.avdFinalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3FynZArruuQ6W0RHu2aQ-C74baEWTaLA',
    appId: '1:1075186320999:web:19f79460f60970cb3ef6c2',
    messagingSenderId: '1075186320999',
    projectId: 'adv-final-examfb',
    authDomain: 'adv-final-examfb.firebaseapp.com',
    storageBucket: 'adv-final-examfb.firebasestorage.app',
  );
}
